
name: Manual workflow

on:
  workflow_dispatch:

jobs:
  production-deploy:
    runs-on: self-hosted

    steps:
    - name: "get latest release/tag (dl from artifactory)"
    - name: "push to production with curl"
